---
banner: img/banners/mountains-1622731_640.jpg
title: "Bonanza Creek Snowshow Hare Examination"
author: "Jessica Jagdeo"
date: "1/24/2020"
output: html_document
categories: ["R"]
tags: ["R Markdown", "plot", "hugo", "eco"]
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<script src="/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="/rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="/rmarkdown-libs/leaflet/leaflet.css" rel="stylesheet" />
<script src="/rmarkdown-libs/leaflet/leaflet.js"></script>
<link href="/rmarkdown-libs/leafletfix/leafletfix.css" rel="stylesheet" />
<script src="/rmarkdown-libs/Proj4Leaflet/proj4-compressed.js"></script>
<script src="/rmarkdown-libs/Proj4Leaflet/proj4leaflet.js"></script>
<link href="/rmarkdown-libs/rstudio_leaflet/rstudio_leaflet.css" rel="stylesheet" />
<script src="/rmarkdown-libs/leaflet-binding/leaflet.js"></script>
<script src="/rmarkdown-libs/leaflet-providers/leaflet-providers_1.9.0.js"></script>
<script src="/rmarkdown-libs/leaflet-providers-plugin/leaflet-providers-plugin.js"></script>


<p>From 1999 to 2017, physical characteristics of snowshoe hares were observed and recorded in the Bonanza Creek Experimental Forest within Alaska (Kielland et al. 2017). This project utilizes the data obtained from this study to visualize the weight and sex of the observed snowshoe hares. In addition, this project explores the summary statistics of the recorded weights for both female and male snowshoe hares.</p>
<div id="load-necessary-packages." class="section level4">
<h4>1. Load necessary packages.</h4>
<pre class="r"><code>library(tidyverse)
library(janitor)
library(kableExtra)
library(naniar)
library(skimr)
library(sf)
library(tmap)</code></pre>
</div>
<div id="read-in-the-data-snowshoe-hare-physical-data-in-bonanza-creek-experimental-forest-1999-present." class="section level4">
<h4>2. Read in the data: Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present.</h4>
<pre class="r"><code>snowshoe &lt;- read_csv(&quot;showshoe_lter.csv&quot;) %&gt;% 
  select(date, sex, age, weight, hindft) 

summary(snowshoe) # Determine if there are missing data: 535 NAs in weight column; 1747 NAs in weight column </code></pre>
<pre><code>##      date               sex                age                weight    
##  Length:3380        Length:3380        Length:3380        Min.   :   0  
##  Class :character   Class :character   Class :character   1st Qu.:1180  
##  Mode  :character   Mode  :character   Mode  :character   Median :1400  
##                                                           Mean   :1346  
##                                                           3rd Qu.:1580  
##                                                           Max.   :2365  
##                                                           NA&#39;s   :535   
##      hindft     
##  Min.   : 60.0  
##  1st Qu.:128.0  
##  Median :135.0  
##  Mean   :130.9  
##  3rd Qu.:140.0  
##  Max.   :160.0  
##  NA&#39;s   :1747</code></pre>
<pre class="r"><code>gg_miss_var(snowshoe) # Visualize missing data: Over 2000 observations are missing an age</code></pre>
<p><img src="/blog/project1_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
</div>
<div id="clean-the-data-based-on-nas-and-and-confirmed-characteristics." class="section level4">
<h4>3. Clean the data based on NAs and and confirmed characteristics.</h4>
<pre class="r"><code>snowshoe_clean &lt;- snowshoe %&gt;% 
  drop_na(weight) %&gt;% # There are 500 missing weights out of over 3000 observations, a relatively small portion of total observations, so we can drop the observations without recorded weights
  mutate(sex = str_to_upper(sex)) %&gt;% # Capitalizing characters for aesthetics
  mutate(age = str_to_upper(age)) %&gt;% # Capitalizing characters for aesthetics
  filter(sex == &quot;M&quot; |
           sex == &quot;F&quot;) # Only keeping observations in which sex was confirmed (only reduces our number of observations by 200)
  
snowshoe_clean$sex &lt;- plyr::revalue(snowshoe_clean$sex, c(&quot;F&quot; = &quot;Female&quot;, &quot;M&quot; = &quot;Male&quot;)) # Renaming &quot;F&quot; and &quot;M&quot; to &quot;Female&quot; and &quot;Male&quot;, respectively for visualization


gg_miss_var(snowshoe_clean) # Rechecking NAs - none for the weight column</code></pre>
<p><img src="/blog/project1_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="graph-characteristics-of-observed-snowshoe-hares." class="section level4">
<h4>4. Graph characteristics of observed snowshoe hares.</h4>
<pre class="r"><code># Creating a jitter plot to depict the weights (y axis) of both female and male snowshoe hares (x axis)

snowshoe_plot &lt;- ggplot(snowshoe_clean, 
                        aes(x = sex, y = weight)) +
  geom_jitter(size = 1, 
              alpha = 0.8,
              aes(color = sex,
                  pch = sex)) +
  theme_classic() +
  labs(x = &quot;Sex&quot;,
       y = &quot;Weight (g)&quot;) +
  theme(legend.position = &quot;none&quot;)

snowshoe_plot</code></pre>
<p><img src="/blog/project1_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><strong>Figure 1. Characteristics of Observed Snowshoe Hares at Bonanza Creek Experimental Forest.</strong> Recordings of snowshoe hare sex and weight were made during the period of 1999 to 2017. Observations in which both sex and weight were conclusively recorded are depicted. Data source: Kielland et al. 2017.</p>
<p>Female and male snowshoe hares appear to have similar weights for the most part (Figure 1). However, several observed female snowshoe hares weighed about 2,500 grams, while no observed male snowshoe hare weighed more than 2,100 grams.</p>
</div>
<div id="create-kable-table-with-summary-statistics-about-observed-snowshoe-hare-sex-and-weight." class="section level4">
<h4>5. Create kable table with summary statistics about observed snowshoe hare sex and weight.</h4>
<pre class="r"><code># Creating a data frame with summary statistics (mean, standard deviation, maximum, minimum, and median) for the weights of female and male snowshoe hares

snowshoe_summary &lt;- snowshoe_clean %&gt;%
  select(sex, weight) %&gt;% 
  group_by(sex) %&gt;% 
  summarise(
    average_weight = round(mean(weight),0),
    sd_weight = round(sd(weight),0),
    max_weight = max(weight),
    min_weight = min(weight),
    median_weight = median(weight)
  )

snowshoe_table &lt;- kable(snowshoe_summary,
                         caption = &quot;**Table 1. Summary statistics for the weights of female and male snowshoe hares observed in the Bonanza Creek Experimental Forest from 1999 to 2017.** Weights were recorded during capture-recapture studies, with a total of 2,628 complete observations obtained for sex and weight. Data source: Kielland et al. 2017.&quot;,
                        col.names = c(&quot;Sex&quot;, &quot;Mean (g)&quot;, &quot;Standard Deviation (g)&quot;, &quot;Maximum (g)&quot;, &quot;Minimum (g)&quot;, &quot;Median (g)&quot;)) %&gt;% 
  kable_styling(bootstrap_options = c(&quot;striped&quot;,&quot;hover&quot;, &quot;condensed&quot;)) %&gt;% 
  column_spec(1, bold = T, border_right = T) 
  

snowshoe_table</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-5">Table 1: </span><strong>Table 1. Summary statistics for the weights of female and male snowshoe hares observed in the Bonanza Creek Experimental Forest from 1999 to 2017.</strong> Weights were recorded during capture-recapture studies, with a total of 2,628 complete observations obtained for sex and weight. Data source: Kielland et al. 2017.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Sex
</th>
<th style="text-align:right;">
Mean (g)
</th>
<th style="text-align:right;">
Standard Deviation (g)
</th>
<th style="text-align:right;">
Maximum (g)
</th>
<th style="text-align:right;">
Minimum (g)
</th>
<th style="text-align:right;">
Median (g)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;">
Female
</td>
<td style="text-align:right;">
1365
</td>
<td style="text-align:right;">
347
</td>
<td style="text-align:right;">
2365
</td>
<td style="text-align:right;">
240
</td>
<td style="text-align:right;">
1420
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;">
Male
</td>
<td style="text-align:right;">
1350
</td>
<td style="text-align:right;">
306
</td>
<td style="text-align:right;">
2060
</td>
<td style="text-align:right;">
240
</td>
<td style="text-align:right;">
1390
</td>
</tr>
</tbody>
</table>
<p>Visually, female and male snowshoe hares observed within the forest appear to have similar weights (Figure 1). The summary statistics depicted in Table 1 highlight that female snowshoe hares have an average weight that is 5 grams greater than the average weight of male snowshoe hares. In addition, the maximum weight recorded for female snowshoe hares (2,365 grams) is greater than the maximum recorded for male snowshoe hares (2,060 grams). Interestingly, both male and female snowshoe hares observed during this study had minimum weight records of 240 grams.</p>
</div>
<div id="create-a-map-of-the-study-location." class="section level4">
<h4>6. Create a map of the study location.</h4>
<pre class="r"><code># Creating a data frame with the 3 coordinates of the study sites within Bonanza Creek Experimental Forest

sites &lt;- tribble(
  ~id, ~lon, ~lat,
  &quot;bonrip&quot;, -148.2682, 64.6991, 
  &quot;bonmat&quot;, -148.1734, 64.41417,
  &quot;bonbs&quot;, -148.2964, 64.7088
)

# Converting this data frame to &quot;sf&quot; object for visualization within a map

sites_sf &lt;- st_as_sf(sites, coords = c(&quot;lon&quot;, &quot;lat&quot;), crs = 4269)

# Visualize site locations within an interactive map

tmap_mode(&quot;view&quot;)

sampling_sites &lt;- tm_basemap(&quot;Esri.WorldImagery&quot;) +
  tm_shape(sites_sf) +
  tm_dots(labels = &quot;id&quot;, col = &quot;darkblue&quot;, size = 0.3)

sampling_sites</code></pre>
<div id="htmlwidget-1" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"createMapPane","args":["tmap401",401]},{"method":"addProviderTiles","args":["Esri.WorldImagery",null,"Esri.WorldImagery",{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"pane":"tilePane"}]},{"method":"addCircleMarkers","args":[[64.6991,64.41417,64.7088],[-148.2682,-148.1734,-148.2964],[10.9544511501033,10.9544511501033,10.9544511501033],["bonrip","bonmat","bonbs"],"sites_sf",{"interactive":true,"className":"","pane":"tmap401","stroke":true,"color":"#666666","weight":1,"opacity":0.5,"fill":true,"fillColor":["#00008B","#00008B","#00008B"],"fillOpacity":[1,1,1]},null,null,["<style> div.leaflet-popup-content {width:auto !important;overflow-y:auto; overflow-x:hidden;}<\/style><div style=\"max-height:25em;padding-right:0px;\"><table>\n\t\t\t   <thead><tr><th colspan=\"2\"><b>bonrip<\/b><\/th><\/thead><\/tr><tr><td style=\"color: #888888;\">id<\/td><td align=\"right\"><nobr>bonrip<\/nobr><\/td><\/tr><\/table><\/div>","<style> div.leaflet-popup-content {width:auto !important;overflow-y:auto; overflow-x:hidden;}<\/style><div style=\"max-height:25em;padding-right:0px;\"><table>\n\t\t\t   <thead><tr><th colspan=\"2\"><b>bonmat<\/b><\/th><\/thead><\/tr><tr><td style=\"color: #888888;\">id<\/td><td align=\"right\"><nobr>bonmat<\/nobr><\/td><\/tr><\/table><\/div>","<style> div.leaflet-popup-content {width:auto !important;overflow-y:auto; overflow-x:hidden;}<\/style><div style=\"max-height:25em;padding-right:0px;\"><table>\n\t\t\t   <thead><tr><th colspan=\"2\"><b>bonbs<\/b><\/th><\/thead><\/tr><tr><td style=\"color: #888888;\">id<\/td><td align=\"right\"><nobr>bonbs<\/nobr><\/td><\/tr><\/table><\/div>"],null,["bonrip","bonmat","bonbs"],{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addLayersControl","args":[[],"sites_sf",{"collapsed":true,"autoZIndex":true,"position":"topleft"}]}],"limits":{"lat":[64.41417,64.7088],"lng":[-148.2964,-148.1734]},"fitBounds":[64.41417,-148.2964,64.7088,-148.1734,[]]},"evals":[],"jsHooks":[]}</script>
<p><strong>Figure 2. Location of Bonanza Creek Experimental Forest.</strong> Snowshoe hares were observed at three different sites within the forest.</p>
<p>Study citation: Kielland K., F. S. Chapin, R. W. Ruess. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present. Environmental Data Initiative.</p>
</div>
